// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MFBSistemas.Models;

public partial class Cliente
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(40)]
    public string Nome { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(50)]
    public string Telefone { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}