// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MFBSistemas.Models;

public partial class LocalDBMSSQLLocalDBContext : DbContext
{
    public LocalDBMSSQLLocalDBContext()
    {
    }

    public LocalDBMSSQLLocalDBContext(DbContextOptions<LocalDBMSSQLLocalDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Produto> Produtos { get; set; }

    public virtual DbSet<Venda> Vendas { get; set; }

    public virtual DbSet<VendaProduto> VendaProdutos { get; set; }

    public virtual DbSet<VwRelatorioProdutosVenda> VwRelatorioProdutosVendas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\MFBSistemas\\MFBSistemas\\Database\\Database.mdf;Integrated Security=True;Connect Timeout=30;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clientes__3214EC07A4CB19B6");
        });

        modelBuilder.Entity<Produto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Produtos__3214EC0785EEF598");
        });

        modelBuilder.Entity<Venda>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vendas__3214EC07EC03497A");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Venda).HasConstraintName("FK_Vendas_Clientes");
        });

        modelBuilder.Entity<VendaProduto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VendaPro__3214EC078398AB00");

            entity.HasOne(d => d.Produto).WithMany(p => p.VendaProdutos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Table_Produtos");

            entity.HasOne(d => d.Venda).WithMany(p => p.VendaProdutos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Table_Vendas");
        });

        modelBuilder.Entity<VwRelatorioProdutosVenda>(entity =>
        {
            entity.ToView("vw_RelatorioProdutosVendas");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}