// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MFBSistemas.Models;

public partial class Produto
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Descricao { get; set; }

    [Column(TypeName = "money")]
    public decimal PrecoUnit { get; set; }

    [InverseProperty("Produto")]
    public virtual ICollection<VendaProduto> VendaProdutos { get; set; } = new List<VendaProduto>();
}