// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MFBSistemas.Models;

public partial class VendaProduto
{
    [Key]
    public int Id { get; set; }

    public int VendaId { get; set; }

    public int ProdutoId { get; set; }

    [Column(TypeName = "money")]
    public decimal PrecoUnit { get; set; }

    public int Quantidade { get; set; }

    [Column(TypeName = "money")]
    public decimal Total { get; set; }

    [ForeignKey("ProdutoId")]
    [InverseProperty("VendaProdutos")]
    public virtual Produto Produto { get; set; }

    [ForeignKey("VendaId")]
    [InverseProperty("VendaProdutos")]
    public virtual Venda Venda { get; set; }
}