// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MFBSistemas.Models;

public partial class Venda
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataVenda { get; set; }

    public int? ClienteId { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("Venda")]
    public virtual Cliente Cliente { get; set; }

    [InverseProperty("Venda")]
    public virtual ICollection<VendaProduto> VendaProdutos { get; set; } = new List<VendaProduto>();

    public string ClienteNome
    {
        get => Cliente.Nome;
    }
}