// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MFBSistemas.Models;

[Keyless]
public partial class VwRelatorioProdutosVenda
{
    public int ProdutoId { get; set; }

    [Required]
    [StringLength(50)]
    public string Descricao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataVenda { get; set; }

    public int? TotalVendido { get; set; }
}